### ISSUE TITLE
new sources and languages

### ISSUE THREAD

**Issue by LinguList** [digling/burmish#52]
Let's collect sources and languages in this thread. Ideall in form of a list. 

We have
- Achang 
- Atsi (Lustig)
- Mann (morphemes typed, not the proto-forms, which we should add for reference and comparison)
- Hpun may be interesting

And we start for those two by making a first concept list (250 concepts), and filling it up? Or is there any other strategy? Mapping whole dictionaries to concepticon is useless, but one can try to make an automatic mapping to the dictionary entries which would then need to be re-checked. In any case: concept-linking needs to be very thorough, as we have the tools to go cross-semantic later.

**Comment by nh36** [comment]
I am now confused because we also have the google doc. We should make our
plans for adding new sources more concrete and specific. If on GitHub, then
I suppose we should get the Googledoc further along and then also put the
information on Github.

--
Dr Nathan W. Hill
Reader in Tibetan and Historical Linguistics
Department of China & Inner Asia and Department of Linguistics
SOAS, University of London
Thornhaugh Street, Russell Square, London WC1H 0XG, UK
Tel: +44 (0)20 7898 4512

--
Profile -- http://www.soas.ac.uk/staff/staff46254.php
Tibetan Studies at SOAS -- http://www.soas.ac.uk/cia/tibetanstudies/
--

On Tue, Sep 6, 2016 at 9:13 PM, Johann-Mattis List <notifications@github.com

**Comment by LinguList** [comment]
yep, we should definitely discuss and decide how to organize the things,
and what is better, github, or drive, etc.
