### ISSUE TITLE
how to put east asian records into JabRef

### ISSUE THREAD

**Issue by nh36** [digling/burmish#69]
Mattis has shared with Nathan a bibtex file that has Huang 1992 in it. The record for Huang 1992 is called "Reference" as opposed to say "InBook" (by the way, how is InBook different than InCollection, I am a bit worried I am doing it wrong). Anyhow, Nathan can see the Huang 1992 entry just fine, but within JabRef the 'Reference' template is not available for a new entry. So, not sure what to do. Here are two saple entries for your delectation-- 

Dai Qingxia 戴庆厦 and Jie Li 李洁 (2007). 勒期语研究 Leqiyu yanjiu. Beijing: 中央民族大学出版社 Zhongyang minzudaxue chubanshe.  ISBN 9787811083262.

Yabu, Shirō 藪 司郎 (1982). アツィ語基礎語彙集 / Atsigo kiso goishū / Classified dictionary of the Atsi or Zaiwa language (Sadon dialect) with Atsi, Japanese and English indexes. Tokyo: 東京外国語大学アジア・アフリカ言語文化研究所 Tōkyō Gaikokugo Daigaku Ajia Afurika Gengo Bunka Kenkyūjo.

**Comment by LinguList** [comment]
*Reference* is a specific bibtex type that is only used in biblatex, the most intelligtent version of bibtex, which is unfortunately not always supported (at least not by the major publishing houses). It applies exactly to things like etymological dictionaries, or handbooks written by one person or a view, or dictionaries (that is, terminology dictionaries) where on person accumulates knowledge of others. Huang 1992 is therefore a real "reference" as it collects languages, I'd say. As alternative, I'd call it a "book", as it is one volume with the same editors, and I'd call the people who publish the book just the authors, as they wrote it more or less.

inbook is a type that is not supported by most bibtex styles, and it should be replaced by the more common type incollection, which is the chapter or the like in an anthology, where one has editor, author, booktitle (title of the anthology), and page-rank (important for this type).

I'll try and re-open the bibtex file in my bilbiography and it is possible that my JabRef adds some annotation that your jabref then reads, so you can profit from that info. Let's see how this works, so try to re-open in a minute. If not, let's stick to "book", "incollection", and I'll provide more info on a "demand-basis". (I could send you tons of literature on biblatex, but I am afraid it will confuse rather than enlighten, as they mix their nice ideas regarding quoting things with tech-talk).
