### ISSUE TITLE
Digitization of Dai2010

### ISSUE THREAD

**Issue by nh36** [digling/burmish#92]
No arrangements have been made to digitize Dai2010, probably because Chashan has so far not been one of our core languages, but once Astrid has finished with the remaining lexical lists I should probably ask her to digitize this also.

**Comment by LinguList** [comment]
What is Chashan? A dialect of a language we have in the sample, or a language on its own right? If the latter, this would be really useful, as we're advancing on handling the data by Nishi and the others, and it may be something useful.

**Comment by nh36** [comment]
It is supposed to be a language in its own right that is similar to Lashi.
There is a Wikipedia article

https://en.wikipedia.org/wiki/Chashan_language

**Comment by nh36** [comment]
Perhaps the reason I didn't ask Astrid to digitize it is because it didn't seem necessary. The book gives off the vibe of being born digital, but my efforts to convert it are so far unsuccessful. Take a look at the attachment. I have also sent these files to you know who, because I think they might interest him and maybe he will do the digitization for us. 
[lex list from Dai2010.zip](https://github.com/digling/burmish/files/784194/lex.list.from.Dai2010.zip)

**Comment by LinguList** [comment]
Yes, if I could multiply myself, I guess my alter egos could work on regular conversion. But since there are people for whom it is much easier to do that, as they have also better initial OCR, we should wait for either him or her to help us. 

But it's great that it's a language of it's own right. From the concepts, I expect high coverage with the data we have in other sources, so it would fit much better than Hpun, where there is only sporadic data.

**Comment by nh36** [comment]
It turns out that we already had this digitized, courtesy of a certain gentleman.
