### ISSUE TITLE
I have somehow wrecked lines 95 and 103 of  burmish/datasets/Burling1967/orthography.tsv

### ISSUE THREAD

**Issue by nh36** [digling/burmish#99]
Please take a look.

**Comment by LinguList** [comment]
fixed now. Problem is that sometimes, there is a space instead of a tab. In order to fix this, github tells you the line, I usually copy-paste that very line to a spreadsheet-tool and check which one it is, then copy back, as spreadsheet-separated lines are usually rendered as tabstop (as required) when pasting them.

**Comment by LinguList** [comment]
so github counts the different "columns" in this tab-separated file. And sine tabstop often looks like space, one can easily confuse. But pasting FROM spreadsheet should usually be correct. Writing a tabstop INSIDE github is not recommended, as the tab has different meaning in online tools (you use it to jump between forms when filling in stuff, say, username and password, in many websites).
